# NovaSolve GitHub Prospect Scraper Configuration
# Target: Python maintainers who would benefit from auto-fixing broken tests

search:
  # Combined query to find mid-size Python packages with active maintainers
  # Targets PyPI packages, CI/CD tools, and research libraries
  query: "language:python stars:100..1000 pushed:>2024-06-01 (topic:pypi OR topic:pytest OR topic:testing OR topic:ci OR topic:machine-learning OR topic:data-science OR topic:numpy OR topic:pandas)"

  # Sort by: 'stars', 'forks', 'updated', 'help-wanted-issues'
  sort: "updated"

  # Order: 'desc' or 'asc'
  order: "desc"

  # Results per page (max 100)
  per_page: 50

filters:
  # Only include activity from last N days
  activity_days: 60  # More recent activity = more likely to have test issues

limits:
  # Maximum number of repos to analyze
  max_repos: 30  # Focus on quality over quantity

  # Per repo limits
  per_repo_prs: 15  # More PRs to find active maintainers
  per_repo_commits: 10  # Recent commit authors per repo

  # Total people limit across all repos
  max_people: 200  # Keep it focused

# Delay between API calls in seconds (be nice to GitHub)
delay: 1

# Target segments for NovaSolve (auto-fix broken Python tests)
target_segments:
  - name: "PyPI Package Owners (mid-size)"
    description: "Active Python packages that ship regular releases"
    query: "language:python stars:100..1000 pushed:>2024-06-01 (topic:pypi OR in:description pypi OR in:readme setup.py)"
    why: "Constantly shipping releases, broken tests = broken PyPI wheel = angry users"

  - name: "CI/CD Tool Maintainers"
    description: "Pytest plugins, tox plugins, test runners"
    query: "language:python stars:50..500 pushed:>2024-06-01 (topic:pytest OR topic:testing OR topic:ci OR topic:tox OR in:name pytest- OR in:name tox-)"
    why: "They live in CI/test infra, NovaSolve resonates instantly"

  - name: "Academic/Research Lib Maintainers"
    description: "ML/data wrangling libraries with fragile dependencies"
    query: "language:python stars:50..1000 pushed:>2024-06-01 (topic:machine-learning OR topic:data-science OR topic:scientific-computing OR topic:numpy OR topic:pandas OR topic:pytorch)"
    why: "Constant churn from NumPy/Pandas/Torch breaking changes"
