# CMO Agent Default Configuration
# Copy this file and modify for your specific campaigns

# Job limits and caps
max_steps: 16
max_repos: 600
max_people: 3000
max_api_calls: 10000

# Rate limits (calls per second)
rate_limits:
  github_per_hour: 5000
  instantly_per_second: 10
  attio_per_minute: 60
  linear_per_minute: 30

# Timeouts (seconds)
timeouts:
  github_api: 15
  instantly_api: 30
  attio_api: 20
  linear_api: 20
  openai_llm: 60

# LLM settings
llm:
  model: "gpt-4o-mini"
  temperature: 0.0

# Retry configuration
retries:
  max_attempts: 3
  backoff_multiplier: 2.0
  jitter: true
  max_backoff_seconds: 300 # 5 minutes max
  rate_limit_retry_after: 60 # Wait 60s after rate limit

# Error handling configuration
error_handling:
  retryable_errors:
    - ConnectionError
    - TimeoutError
    - httpx.ConnectTimeout
    - httpx.ReadTimeout
    - httpx.PoolTimeout
    - aiohttp.ClientConnectorError
  rate_limit_errors:
    - RateLimitError
    - TooManyRequests
    - GitHubRateLimitError
    - CircuitBreakerOpenError
  permanent_errors:
    - AuthenticationError
    - AuthorizationError
    - NotFoundError
    - ValidationError
  circuit_breaker:
    failure_threshold: 5
    recovery_timeout: 300 # 5 minutes

# Default ICP (Ideal Customer Profile)
default_icp:
  languages: ["python"]
  topics: ["ci", "testing", "pytest", "devtools", "llm"]
  stars_range: "100..2000"
  activity_days: 90
  exclude_topics: ["deprecated", "unmaintained"]

# Campaign defaults
campaign_defaults:
  subject_template: "Quick fix for {{repo}} CI flakes"
  body_template: |
    Hi {{first_name}},

    I noticed {{repo}} has shown recent activity with {{language}} development. Nova is a small GitHub App that only wakes up when CI fails on a PR, pinpoints the cause, and pushes a minimal patch as a PR.

    {{why_now}}

    Zero lock-in, BYO API key, OSS license. Want a one-off trial on a test PR?

    — Sebastian
    {{unsub_link}}

# Export configuration
export_dir: "./exports"
checkpoint_every: 200 # Save CSV every N leads

# Artifact management configuration
artifacts:
  cleanup_interval_seconds: 3600 # 1 hour
  retention_days: 30
  max_per_job: 20
  compress_large_datasets: true
  auto_cleanup: true
  storage_backend: filesystem # filesystem, s3, etc.

# Logging
log_level: "INFO"
log_file: "./logs/cmo_agent.log"

# Worker configuration
workers:
  pool_size: 3 # Number of concurrent workers
  max_concurrent_jobs_per_worker: 3 # Concurrent jobs per worker
  max_jobs_per_worker: 10 # Jobs before worker restart
  heartbeat_interval: 30 # Heartbeat frequency (seconds)
  graceful_shutdown: 60 # Shutdown timeout (seconds)

# Queue configuration
queue:
  type: persistent # persistent, redis, postgres, sqlite, memory
  storage_dir: "./data/jobs" # For persistent queue
  max_retries: 3
  retry_delay: 5 # seconds
  priority_levels: 5
  max_queue_size: 1000
  enable_prioritization: true
  enable_scheduling: true
  enable_tagging: true
  default_priority: "normal" # low, normal, high, urgent, critical
  priority_boost_on_retry: true
  worker_tag_matching: true

# Persistence configuration
persistence:
  type: json # json, postgres, sqlite, redis
  checkpoint_interval: 300 # seconds
  max_checkpoints: 50
  compression: false

# Job configuration
job_config:
  timeouts:
    job_timeout: 3600 # 1 hour max per job
    step_timeout: 300 # 5 minutes max per step
    api_timeout: 30 # 30 seconds max per API call
  limits:
    max_concurrent_jobs: 10
    max_queue_size: 1000
    rate_limit_buffer: 0.8 # Use 80% of rate limits
  checkpoints:
    time_interval: 300 # Every 5 minutes
    step_interval: 50 # Every 50 steps
    volume_interval: 1000 # Every 1000 leads
    enabled: true
    adaptive: true # Use adaptive checkpointing based on job progress
    # New: control stage-based checkpointing frequency
    enable_stage: true
    stage_min_interval: 180 # Minimum seconds between stage-triggered checkpoints
    # stages: ["enrichment", "validation", "completed"] # Optional allowlist

# Monitoring and metrics
monitoring:
  enabled: true
  metrics_interval: 60 # seconds
  enable_prometheus: false
  enable_datadog: false

# Feature flags
features:
  dry_run: false
  enable_langfuse: false
  enable_background_jobs: true
  enable_rate_limiting: true
  enable_distributed_workers: false
  enable_fault_tolerance: true
  enable_progress_streaming: true
  enable_auto_progress: true

# Email discovery configuration
email_search:
  days: 365 # look back window for commits
  batch_size: 10 # users processed per batch
  repos_per_user: 12 # max repos per user to scan
  commits_per_repo: 50 # max commits per repo to fetch
  include_committer_email: true # also consider committer.email in addition to author.email
  noop_streak_threshold: 4 # attempts with no new emails before marking exhausted
