## YAML-driven smoke test config (no typed GOAL required)
##
## How to run:
## - From repo root:
##     make run-config CONFIG=cmo_agent/config/smoke_prompt.yaml
##     make dry-run    CONFIG=cmo_agent/config/smoke_prompt.yaml
## - Inline overrides (no file edits needed):
##     make run-config CONFIG=cmo_agent/config/smoke_prompt.yaml SET="language=Go target_leads=50"
##     make dry-run    CONFIG=cmo_agent/config/smoke_prompt.yaml SET="stars_range=500..5000 activity_days=60"
##
## Notes:
## - pushed_since auto-computes to today - activity_days when null
## - No goal string is required. If goal_template is omitted, a friendly
##   display-only line is synthesized from params for logs/UI.

version: 1

# Parameters used to render the smoke-test prompt and display plan
params:
  language: "Python"
  stars_range: "300..2000"
  activity_days: 90
  target_leads: 20
  budget_per_day: 10

# If provided, overrides computed pushed_since; otherwise computed as today - activity_days
pushed_since: null # e.g., "2025-06-01"

## Optional: You may still provide a goal_template to control the display line
## goal_template: |
##   Find maintainers of {{language}} repos stars:{{stars_range}} pushed:>={{pushed_since}}; prioritize active {{activity_days}} days; export CSV.
