version: 1

# Main config aligned to ICP #1 (PyPI Maintainers – default)

search:
  type: repositories
  query: >
    language:python stars:50..2000 is:public archived:false
    in:readme pytest
    pushed:>{date:60}
  sort: updated
  order: desc
  per_page: 50

filters:
  activity_days: 90
  skip_without_email: true

limits:
  max_repos: 100
  per_repo_prs: 15
  per_repo_commits: 15
  max_people: 20

delay: 1.0

enrichment:
  pull:
    repo_topics: true
    releases: true
    files_presence: true
    pypi_metadata: true
  recent_window_days: 90
