# GitHub Repository Scraper Configuration for Attio
# Test configuration to verify repo data collection

search:
  # Search for popular Python ML/AI repositories
  query: "language:python topic:machine-learning stars:>1000 pushed:>2024-01-01"
  sort: "stars"
  order: "desc"
  per_page: 30

filters:
  activity_days: 90

limits:
  max_repos: 10 # Just get 10 repos for testing

# API delay in seconds
delay: 0.5
