# NovaSolve Config: Academic/Research Lib Maintainers
# Target: ML/data wrangling libraries with fragile dependencies
# Pain point: Constant churn from NumPy/Pandas/Torch breaking changes

search:
  # Find ML/data science libraries that likely have complex test suites
  query: "language:python stars:50..1000 pushed:>2024-06-01 machine-learning in:topics,description"

  sort: "updated"
  order: "desc"
  per_page: 50

filters:
  activity_days: 45 # More recent - these break frequently

limits:
  max_repos: 25
  per_repo_prs: 12
  per_repo_commits: 10
  max_people: 150

delay: 1
