# Web3 / Blockchain Configuration

search:
  # Target blockchain and DeFi projects
  query: "(topic:blockchain OR topic:web3 OR topic:ethereum OR topic:defi OR topic:smart-contracts) stars:>200 pushed:>2024-01-01"
  sort: "updated"
  order: "desc"
  per_page: 30

filters:
  activity_days: 45

limits:
  max_repos: 50
  per_repo_prs: 10
  per_repo_commits: 10
  max_people: 500

delay: 1.5 # Be extra nice to avoid rate limits

# High-value indicators
value_signals:
  - "mainnet"
  - "audit"
  - "TVL"
  - "protocol"
  - "DAO"
  - "governance"
  - "staking"
  - "yield"
