name: Attio Export

on:
  # Run weekly on Mondays at 8 AM UTC
  schedule:
    - cron: "0 8 * * 1"

  # Manual trigger
  workflow_dispatch:

env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

jobs:
  attio-export:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v4
        with:
          python-version: "3.12"
          cache: "pip"

      - name: Setup and run
        run: |
          make setup
          make attio

      - name: Upload results
        uses: actions/upload-artifact@v4
        with:
          name: attio-exports-$(date +%Y%m%d)
          path: exports/
          retention-days: 30
